
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AS COMMA DOT DP EQUALS FILTER GREATER IDENTIFIER LESS LOAD LPAREN NUMBER PLOT RPAREN STRING WHEREprogram : statement_liststatement_list : statement\n                  | statement_list statementstatement : DP DOT IDENTIFIER LPAREN  IDENTIFIER RPAREN\n           | DP DOT IDENTIFIER LPAREN IDENTIFIER COMMA IDENTIFIER RPARENstatement : LOAD STRING AS IDENTIFIERstatement : FILTER IDENTIFIER WHERE IDENTIFIER comparison NUMBER AS IDENTIFIERstatement : PLOT IDENTIFIER AS IDENTIFIERcomparison : GREATER\n               | LESS\n               | EQUALS'
    
_lr_action_items = {'DP':([0,2,3,8,18,20,26,31,32,],[4,4,-2,-3,-6,-8,-4,-5,-7,]),'LOAD':([0,2,3,8,18,20,26,31,32,],[5,5,-2,-3,-6,-8,-4,-5,-7,]),'FILTER':([0,2,3,8,18,20,26,31,32,],[6,6,-2,-3,-6,-8,-4,-5,-7,]),'PLOT':([0,2,3,8,18,20,26,31,32,],[7,7,-2,-3,-6,-8,-4,-5,-7,]),'$end':([1,2,3,8,18,20,26,31,32,],[0,-1,-2,-3,-6,-8,-4,-5,-7,]),'DOT':([4,],[9,]),'STRING':([5,],[10,]),'IDENTIFIER':([6,7,9,14,15,16,17,27,30,],[11,12,13,18,19,20,21,29,32,]),'AS':([10,12,28,],[14,16,30,]),'WHERE':([11,],[15,]),'LPAREN':([13,],[17,]),'GREATER':([19,],[23,]),'LESS':([19,],[24,]),'EQUALS':([19,],[25,]),'RPAREN':([21,29,],[26,31,]),'COMMA':([21,],[27,]),'NUMBER':([22,23,24,25,],[28,-9,-10,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement_list':([0,],[2,]),'statement':([0,2,],[3,8,]),'comparison':([19,],[22,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement_list','program',1,'p_program','parser.py',8),
  ('statement_list -> statement','statement_list',1,'p_statement_list','parser.py',12),
  ('statement_list -> statement_list statement','statement_list',2,'p_statement_list','parser.py',13),
  ('statement -> DP DOT IDENTIFIER LPAREN IDENTIFIER RPAREN','statement',6,'p_statement_dp_logic','parser.py',22),
  ('statement -> DP DOT IDENTIFIER LPAREN IDENTIFIER COMMA IDENTIFIER RPAREN','statement',8,'p_statement_dp_logic','parser.py',23),
  ('statement -> LOAD STRING AS IDENTIFIER','statement',4,'p_statement_load','parser.py',41),
  ('statement -> FILTER IDENTIFIER WHERE IDENTIFIER comparison NUMBER AS IDENTIFIER','statement',8,'p_statement_filter','parser.py',46),
  ('statement -> PLOT IDENTIFIER AS IDENTIFIER','statement',4,'p_statement_plot','parser.py',50),
  ('comparison -> GREATER','comparison',1,'p_comparison','parser.py',55),
  ('comparison -> LESS','comparison',1,'p_comparison','parser.py',56),
  ('comparison -> EQUALS','comparison',1,'p_comparison','parser.py',57),
]
